spring.application.name=Hayaterra
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.jujumarchal52@gmail.com
spring.mail.password=your-email-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
